### ISSUE TITLE
Check additional papers for lecture 3

### ISSUE THREAD

**Issue by ChristianHilpert** [ChristianHilpert/Topics-in-Behavioural-Decision-Theory#2]
There are a few new papers on memory-related theories by Bordalo, Gennaioli, and Shleifer in the QJE, and a new model from a guy in Berkeley in ReStud. Check if they are relevant.

**Comment by YuheYoung** [comment]
Okay.

**Comment by ChristianHilpert** [comment]
May want to come back to this point for a revised version of the lecture. This lecture is full. Adding additional material requires a restructuring of the whole course.
